Repository RAF-SI-2022/Banka-1-Backend, pull requests merged in 2023-06, with the labels that each got.

#89 account delete fix
  companies-service/src/routes/account.route.ts
  user-service/src/main/java/org/banka1/userservice/domains/entities/User.java
Labels: size/XS

#90 Ispravljeni testovi za OrderService + mala izmena u pom fajlovima da bi Sonar pravilno citao
  exchange-service/pom.xml
  exchange-service/src/test/java/org/banka1/exchangeservice/IntegrationTest.java
  exchange-service/src/test/java/org/banka1/exchangeservice/OrderServiceTest.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/orderservice/OrderServiceTestsSteps.java
  exchange-service/src/test/java/org/banka1/exchangeservice/service/OrderServiceUnitTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/services/OptionServiceTest.java
  exchange-service/src/test/resources/features/order-service-tests.feature
  user-service/pom.xml
Labels: size/XL

#94 Izmenjen link za reset i aktivaciju šifre
  kubernetes/user-service.yaml
Labels: size/XS

#95 Dodata provera da li su podaci već učitani kod CommandLineRunnera
  exchange-service/src/main/java/org/banka1/exchangeservice/bootstrap/BootstrapData.java
  user-service/src/main/java/org/banka1/userservice/bootstrap/BootstrapData.java
Labels: size/S

#97 added tests
  exchange-service/pom.xml
  user-service/src/main/java/org/banka1/userservice/controllers/UserController.java
  user-service/src/test/java/org/banka1/userservice/controllers/UserControllerTest.java
  user-service/src/test/java/org/banka1/userservice/services/UserListingServiceTest.java
Labels: size/L

#98 added tests
  exchange-service/pom.xml
  user-service/pom.xml
  user-service/src/test/java/org/banka1/userservice/IntegrationTest.java
  user-service/src/test/java/org/banka1/userservice/services/UserContractsServiceTest.java
Labels: size/M

#99 added tests for exchange service
  exchange-service/src/test/java/org/banka1/exchangeservice/controllers/ForexControllerTest.java
  exchange-service/src/test/java/org/banka1/exchangeservice/controllers/OrderControllerTest.java
  exchange-service/src/test/java/org/banka1/exchangeservice/controllers/StockControllerTest.java
Labels: size/L

#100 Changes by vuk
  exchange-service/pom.xml
Labels: size/XS

#101 Changes by vuk
  exchange-service/pom.xml
Labels: size/XS

#102 Osnovni setup mikroservisa za banku + user servis
  bank-service/.gitignore
  bank-service/pom.xml
  bank-service/src/main/java/org/banka1/bankservice/BankServiceApplication.java
  bank-service/src/main/java/org/banka1/bankservice/bootstrap/BootstrapData.java
  bank-service/src/main/java/org/banka1/bankservice/configuration/GlobalConfiguration.java
  bank-service/src/main/java/org/banka1/bankservice/configuration/SpringSecurityConfiguration.java
  bank-service/src/main/java/org/banka1/bankservice/configuration/SwaggerConfiguration.java
  bank-service/src/main/java/org/banka1/bankservice/controllers/ExceptionHandlerController.java
  bank-service/src/main/java/org/banka1/bankservice/controllers/UserController.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/login/LoginRequest.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/login/LoginResponse.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/user/PasswordDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/user/UserCreateDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/user/UserDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/user/UserFilterRequest.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/user/UserUpdateDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/BankUser.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/Department.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/Gender.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/Position.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/UserRole.java
  bank-service/src/main/java/org/banka1/bankservice/domains/exceptions/BadRequestException.java
  bank-service/src/main/java/org/banka1/bankservice/domains/exceptions/ForbiddenException.java
  bank-service/src/main/java/org/banka1/bankservice/domains/exceptions/InternalServerError.java
  bank-service/src/main/java/org/banka1/bankservice/domains/exceptions/NotFoundException.java
  bank-service/src/main/java/org/banka1/bankservice/domains/exceptions/ValidationException.java
  bank-service/src/main/java/org/banka1/bankservice/domains/mappers/UserMapper.java
  bank-service/src/main/java/org/banka1/bankservice/filters/JwtFilter.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/UserRepository.java
  bank-service/src/main/java/org/banka1/bankservice/services/EmailService.java
  bank-service/src/main/java/org/banka1/bankservice/services/UserService.java
  bank-service/src/main/java/org/banka1/bankservice/utils/JwtUtil.java
  bank-service/src/main/resources/application.properties
  bank-service/src/test/resources/application-test_it.properties
  bank-service/src/test/resources/junit-platform.properties
  bank-service/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  pom.xml
Labels: lgtm, size/XXL

#103 Dodati potrebni entieti
  bank-service/csv-files/currencies.csv
  bank-service/pom.xml
  bank-service/src/main/java/org/banka1/bankservice/bootstrap/BootstrapData.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/currency/CurrencyCsvBean.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/AccountType.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/BusinessAccount.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/Company.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/Currency.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/CurrentAccount.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/ForeignCurrencyAccCurrency.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/ForeignCurrencyAccount.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/Status.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/embeddable/ForeignCurrencyAccCurrencyKey.java
  bank-service/src/main/java/org/banka1/bankservice/domains/mappers/CurrencyMapper.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/BusinessAccountRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/CompanyRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/CurrencyRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/CurrentAccountRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/ForeignCurrencyAccountRepository.java
  bank-service/src/main/java/org/banka1/bankservice/services/BusinessAccountService.java
  bank-service/src/main/java/org/banka1/bankservice/services/CompanyService.java
  bank-service/src/main/java/org/banka1/bankservice/services/CurrencyService.java
  bank-service/src/main/java/org/banka1/bankservice/services/CurrentAccountService.java
  bank-service/src/main/java/org/banka1/bankservice/services/ForeignCurrencyAccountService.java
  bank-service/src/main/resources/csv/currencies.csv
Labels: lgtm, size/XL
