Repository RAF-SI-2022/Banka-1-Backend, pull requests merged in 2023-05, with the labels that each got.

#70 Dodati rute za supervizora
  user-service/src/main/java/org/banka1/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/org/banka1/userservice/configuration/SpringSecurityConfiguration.java
  user-service/src/main/java/org/banka1/userservice/controllers/UserController.java
  user-service/src/main/java/org/banka1/userservice/services/UserService.java
Labels: size/M

#69 Implementacija Message Queue-a & testovi za OrderService
  exchange-service/pom.xml
  exchange-service/src/main/java/org/banka1/exchangeservice/ExchangeServiceApplication.java
  exchange-service/src/main/java/org/banka1/exchangeservice/configuration/JacksonConfiguration.java
  exchange-service/src/main/java/org/banka1/exchangeservice/configuration/RabbitMQConfiguration.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/Forex.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/Listing.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/ForexService.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OrderService.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/StockService.java
  exchange-service/src/main/resources/application.properties
  exchange-service/src/test/java/org/banka1/exchangeservice/OrderServiceTest.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/orderservice/OrderServiceTestsSteps.java
  exchange-service/src/test/resources/features/order-service-tests.feature
Labels: size/XL

#71 Izmene za supervizora
  user-service/src/main/java/org/banka1/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/org/banka1/userservice/configuration/SpringSecurityConfiguration.java
  user-service/src/main/java/org/banka1/userservice/controllers/UserController.java
  user-service/src/main/java/org/banka1/userservice/services/UserService.java
  user-service/src/test/java/org/banka1/userservice/IntegrationTest.java
  user-service/src/test/java/org/banka1/userservice/controllers/UserControllerTest.java
  user-service/src/test/java/org/banka1/userservice/services/UserServiceTest.java
Labels: size/XL

#72 Option
  exchange-service/src/main/java/org/banka1/exchangeservice/controllers/OrderController.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/BetDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/OptionChainDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/OptionResponseDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/OptionTypeDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/Response.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/ResultDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/Option.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/OptionBet.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/OptionBetRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OptionService.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OrderService.java
  exchange-service/src/test/java/org/banka1/exchangeservice/service/CurrencyServiceUnitTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/services/OrderServiceTest.java
  user-service/src/main/java/org/banka1/userservice/filters/JwtFilter.java
Labels: size/L

#73 contracts service
  contracts-service/.dockerignore
  contracts-service/Dockerfile
  contracts-service/package-lock.json
  contracts-service/package.json
  contracts-service/src/middleware/auth.middleware.ts
  contracts-service/src/model/contracts/contract.model.ts
  contracts-service/src/model/contracts/finalised-contract.model.ts
  contracts-service/src/model/errors/error-messages.ts
  contracts-service/src/model/users/user-roles.ts
  contracts-service/src/mongo-db.ts
  contracts-service/src/routes/contract.route.ts
  contracts-service/src/routes/finalised-contract.route.ts
  contracts-service/src/service.ts
  contracts-service/src/utils/jwt-util.ts
  contracts-service/tsconfig.json
  docker-compose.yml
  exchange-service/src/main/java/org/banka1/exchangeservice/filters/CustomAuthorizationFilter.java
  user-service/src/main/java/org/banka1/userservice/utils/JwtUtil.java
Labels: size/XXL

#74 Dodate dve rute u stock kontroleru
  exchange-service/src/main/java/org/banka1/exchangeservice/controllers/StockController.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/StockRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/StockService.java
Labels: size/M

#77 Feature/options
  exchange-service/src/main/java/org/banka1/exchangeservice/controllers/OrderController.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/BetDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/OptionChainDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/OptionResponseDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/OptionTypeDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/Response.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/ResultDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/Option.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/OptionBet.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/OptionBetRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OptionService.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OrderService.java
  exchange-service/src/test/java/org/banka1/exchangeservice/service/CurrencyServiceUnitTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/services/OrderServiceTest.java
  user-service/src/main/java/org/banka1/userservice/filters/JwtFilter.java
Labels: size/L

#80 transactions api
  contracts-service/package-lock.json
  contracts-service/package.json
  contracts-service/src/environment.ts
  contracts-service/src/model/contracts/contract-transactions.ts
  contracts-service/src/model/contracts/contract.model.ts
  contracts-service/src/model/errors/error-messages.ts
  contracts-service/src/mongo-db.ts
  contracts-service/src/routes/contract.route.ts
  contracts-service/src/routes/finalised-contract.route.ts
  contracts-service/tsconfig.json
Labels: size/L

#83 companies
  companies-service/.dockerignore
  companies-service/Dockerfile
  companies-service/package-lock.json
  companies-service/package.json
  companies-service/src/environment.ts
  companies-service/src/middleware/auth.middleware.ts
  companies-service/src/model/companies/account.model.ts
  companies-service/src/model/companies/company.model.ts
  companies-service/src/model/companies/contact.model.ts
  companies-service/src/model/contracts/contract.model.ts
  companies-service/src/model/errors/error-messages.ts
  companies-service/src/mongo-db.ts
  companies-service/src/routes/account.route.ts
  companies-service/src/routes/company.route.ts
  companies-service/src/routes/contact.route.ts
  companies-service/src/service.ts
  companies-service/tsconfig.json
  docker-compose.yml
Labels: size/XXL

#84 Added redis
  exchange-service/pom.xml
  exchange-service/src/main/java/org/banka1/exchangeservice/ExchangeServiceApplication.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/StockService.java
  exchange-service/src/main/resources/application.properties
Labels: size/S

#81 fix
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/Option.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OptionService.java
Labels: size/M

#87 Added feature finishing options before expiration date
  exchange-service/src/main/java/org/banka1/exchangeservice/controllers/OrderController.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OrderService.java
Labels: size/M
