Repository RAF-SI-2022/Banka-1-Backend, pull requests merged in 2023-03, with the labels that each got.

#1 init
  .gitignore
  pom.xml
  user-service/.gitignore
  user-service/.mvn/wrapper/maven-wrapper.jar
  user-service/.mvn/wrapper/maven-wrapper.properties
  user-service/mvnw
  user-service/mvnw.cmd
  user-service/pom.xml
  user-service/src/main/java/org/banka1/userservice/UserServiceApplication.java
  user-service/src/main/java/org/banka1/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/org/banka1/userservice/configuration/GlobalConfiguration.java
  user-service/src/main/java/org/banka1/userservice/configuration/SpringSecurityConfiguration.java
  user-service/src/main/java/org/banka1/userservice/controllers/UserController.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/login/LoginRequest.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/login/LoginResponse.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/user/PasswordDto.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/user/UserCreateDto.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/user/UserDto.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/user/UserFilterRequest.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/user/UserUpdateDto.java
  user-service/src/main/java/org/banka1/userservice/domains/entities/Position.java
  user-service/src/main/java/org/banka1/userservice/domains/entities/User.java
  user-service/src/main/java/org/banka1/userservice/domains/entities/UserRole.java
  user-service/src/main/java/org/banka1/userservice/domains/exceptions/BadRequestException.java
  user-service/src/main/java/org/banka1/userservice/domains/exceptions/ForbiddenException.java
  user-service/src/main/java/org/banka1/userservice/domains/exceptions/InternalServerError.java
  user-service/src/main/java/org/banka1/userservice/domains/exceptions/NotFoundExceptions.java
  user-service/src/main/java/org/banka1/userservice/domains/mappers/UserMapper.java
  user-service/src/main/java/org/banka1/userservice/filters/JwtFilter.java
  user-service/src/main/java/org/banka1/userservice/repositories/UserRepository.java
  user-service/src/main/java/org/banka1/userservice/services/EmailService.java
  user-service/src/main/java/org/banka1/userservice/services/UserService.java
  user-service/src/main/java/org/banka1/userservice/utils/JwtUtil.java
  user-service/src/main/resources/application.properties
Labels: needs-ok-to-test, size/XXL

#19 Feature/user unit tests
  user-service/src/test/java/org/banka1/userservice/services/services/UserServiceTest.java
Labels: size/L

#18 added swagger
  user-service/pom.xml
  user-service/src/main/java/org/banka1/userservice/configuration/SpringSecurityConfiguration.java
  user-service/src/main/java/org/banka1/userservice/configuration/SwaggerConfig.java
  user-service/src/main/java/org/banka1/userservice/controllers/UserController.java
  user-service/src/main/resources/application.properties
Labels: size/L

#26 Feature/user tests
  user-service/src/test/java/org/banka1/userservice/services/services/UserServiceTest.java
Labels: size/L

#36 Implementacija inicijalnog ucitavanja valuta u bazu podataka
  currencies.csv
  exchange-service/pom.xml
  exchange-service/src/main/java/org/banka1/exchangeservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/CurrencyCsvBean.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/Currency.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/CurrencyRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/CurrencyService.java
  exchange-service/src/test/java/org/banka1/exchangeservice/CurrencyServiceTest.java
  exchange-service/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: size/L

#37 Sprint/exchange service
  exchange-service/src/main/java/org/banka1/exchangeservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/org/banka1/exchangeservice/controllers/ExchangeController.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/ExchangeCSV.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/Exchange.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/mappers/ExchangeMapper.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/ExchangeRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/ExchangeService.java
  exchange-service/src/main/resources/exchange.csv
Labels: size/XL

#40 Flask API service
  README.md
  flask-api-service/app.py
  flask-api-service/controllers/forex.py
  flask-api-service/controllers/stocks.py
  flask-api-service/requirements.txt
Labels: size/L
