Repository RAF-SI-2022/Banka-1-Backend, pull requests merged in 2023-04, with the labels that each got.

#44 ispravka user service-a, swagger za exchange, getById stock
  exchange-service/src/main/java/org/banka1/exchangeservice/configuration/SwaggerConfig.java
  exchange-service/src/main/java/org/banka1/exchangeservice/controllers/StockController.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/StockService.java
  user-service/src/main/java/org/banka1/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/org/banka1/userservice/services/UserService.java
Labels: size/M

#45 Filter for exchabge service
  exchange-service/src/main/java/org/banka1/exchangeservice/configuration/SpringSecurityConfiguration.java
  exchange-service/src/main/java/org/banka1/exchangeservice/errors/MyAccessDeniedHandler.java
  exchange-service/src/main/java/org/banka1/exchangeservice/filters/CustomAuthorizationFilter.java
Labels: size/L

#48 Sprint/exchange service origin
  exchange-service/src/main/java/org/banka1/exchangeservice/ExchangeServiceApplication.java
  exchange-service/src/main/java/org/banka1/exchangeservice/controllers/OrderController.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/order/OrderFilterRequest.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/order/OrderResponse.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/user/BankAccountDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/user/Position.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/user/UserDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/user/UserListingCreateDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/user/UserListingDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/ForexRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/OrderRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/StockRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OrderService.java
  exchange-service/src/main/resources/application.properties
  user-service/src/main/java/org/banka1/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/org/banka1/userservice/controllers/UserController.java
  user-service/src/main/java/org/banka1/userservice/controllers/UserListingController.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/user/listing/UserListingCreateDto.java
  user-service/src/main/java/org/banka1/userservice/domains/dtos/user/listing/UserListingDto.java
  user-service/src/main/java/org/banka1/userservice/domains/entities/BankAccount.java
  user-service/src/main/java/org/banka1/userservice/domains/entities/User.java
  user-service/src/main/java/org/banka1/userservice/domains/entities/UserRole.java
  user-service/src/main/java/org/banka1/userservice/domains/mappers/UserListingMapper.java
  user-service/src/main/java/org/banka1/userservice/repositories/BankAccountRepository.java
  user-service/src/main/java/org/banka1/userservice/repositories/UserListingRepository.java
  user-service/src/main/java/org/banka1/userservice/services/UserListingService.java
  user-service/src/main/java/org/banka1/userservice/services/UserService.java
Labels: size/XL

#47 dodat kes za time series podatke
  flask-api-service/app.py
  flask-api-service/cache.py
  flask-api-service/controllers/forex.py
  flask-api-service/controllers/stocks.py
  flask-api-service/requirements.txt
Labels: size/M

#49 Testovi za currency service
  exchange-service/pom.xml
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/mappers/CurrencyMapper.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/CurrencyService.java
  exchange-service/src/test/java/org/banka1/exchangeservice/CurrencyServiceUnitTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/currencyservice/CurrencyServiceTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/currencyservice/CurrencyServiceTestsConfig.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/currencyservice/CurrencyServiceTestsSteps.java
  exchange-service/src/test/resources/features/currency-service-tests.feature
  exchange-service/src/test/resources/junit-platform.properties
Labels: size/L

#50 Ispravka
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/currencyservice/CurrencyServiceTestsConfig.java
Labels: size/XS

#53 cucumber tests
  exchange-service/src/test/java/org/banka1/exchangeservice/ExchangeServiceApplicationTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/forexservice/ForexServiceTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/forexservice/ForexServiceTestsConfig.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/forexservice/ForexServiceTestsSteps.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/orderservice/OrderServiceTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/orderservice/OrderServiceTestsConfig.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/orderservice/OrderServiceTestsSteps.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/stockservice/StockServiceTests.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/stockservice/StockServiceTestsConfig.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/stockservice/StockServiceTestsSteps.java
  exchange-service/src/test/resources/application-test_it.properties
  exchange-service/src/test/resources/features/forex-service-tests.feature
  exchange-service/src/test/resources/features/order-service-tests.feature
  exchange-service/src/test/resources/features/stock-service-tests.feature
Labels: size/L

#61 Feature/sonar qube new
  .prow/exchange-service.yaml
  .prow/user-service.yaml
  docker-compose.yml
  exchange-service/Dockerfile
  exchange-service/csv-files/currencies.csv
  exchange-service/csv-files/exchange.csv
  exchange-service/csv-files/forex-pair-test.csv
  exchange-service/csv-files/forex-pair.csv
  exchange-service/csv-files/stocks.csv
  exchange-service/csv-files/stocks_test.csv
  exchange-service/pom.xml
  exchange-service/src/main/java/org/banka1/exchangeservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/org/banka1/exchangeservice/controllers/OptionController.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/OptionDto.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/dtos/option/OptionFilterRequest.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/Option.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/entities/OptionType.java
  exchange-service/src/main/java/org/banka1/exchangeservice/domains/mappers/OptionMapper.java
  exchange-service/src/main/java/org/banka1/exchangeservice/repositories/OptionRepository.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/ForexService.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OptionService.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/OrderService.java
  exchange-service/src/main/java/org/banka1/exchangeservice/services/StockService.java
  exchange-service/src/main/resources/application.properties
  flask-api-service/Dockerfile
  user-service/Dockerfile
  user-service/pom.xml
  user-service/src/main/java/org/banka1/userservice/bootstrap/BootstrapData.java
  user-service/src/main/resources/application.properties
Labels: size/XXL

#62 added tests for options
  exchange-service/src/test/java/org/banka1/exchangeservice/IntegrationTest.java
  exchange-service/src/test/java/org/banka1/exchangeservice/controllers/OptionControllerTest.java
  exchange-service/src/test/java/org/banka1/exchangeservice/cucumber/stockservice/StockServiceTestsSteps.java
  exchange-service/src/test/java/org/banka1/exchangeservice/services/OptionServiceTest.java
Labels: size/L

#63 changes pom xml
  exchange-service/pom.xml
  user-service/pom.xml
Labels: size/XS
