Repository RAF-SI-2022/Banka-1-Backend, pull requests merged in 2023-07, with the labels that each got.

#107 Kartice & krediti
  bank-service/src/main/java/org/banka1/bankservice/controllers/CardController.java
  bank-service/src/main/java/org/banka1/bankservice/controllers/CreditController.java
  bank-service/src/main/java/org/banka1/bankservice/controllers/CurrencyExchangeController.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/card/CardCreateDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/card/CardDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/card/CardPaymentDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/credit/CreditDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/credit/CreditInstallmentDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/credit/CreditRequestCreateDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/credit/CreditRequestDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/currency_exchange/ConversionTransferConfirmDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/card/Card.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/card/CardType.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/credit/Credit.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/credit/CreditInstallment.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/credit/CreditRequest.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/credit/CreditRequestStatus.java
  bank-service/src/main/java/org/banka1/bankservice/domains/entities/credit/CreditType.java
  bank-service/src/main/java/org/banka1/bankservice/domains/mappers/CardMapper.java
  bank-service/src/main/java/org/banka1/bankservice/domains/mappers/CreditMapper.java
  bank-service/src/main/java/org/banka1/bankservice/domains/mappers/CurrencyExchangeMapper.java
  bank-service/src/main/java/org/banka1/bankservice/domains/mappers/PaymentMapper.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/CardRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/ConversionTransferRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/CreditInstallmentRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/CreditRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/CreditRequestRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/ForeignCurrencyBalanceRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/PaymentReceiverRepository.java
  bank-service/src/main/java/org/banka1/bankservice/repositories/PaymentRepository.java
  bank-service/src/main/java/org/banka1/bankservice/services/AccountService.java
  bank-service/src/main/java/org/banka1/bankservice/services/CardService.java
  bank-service/src/main/java/org/banka1/bankservice/services/CreditService.java
  bank-service/src/main/java/org/banka1/bankservice/services/CurrencyExchangeService.java
  bank-service/src/main/java/org/banka1/bankservice/services/PaymentService.java
Labels: size/XXL

#108 set up sonar qube for bank service and configured docker for banka se…
  .prow/bank-service.yaml
  bank-service/Dockerfile
  docker-compose.yml
Labels: size/L

#112 Feature/bank service
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/card/CardCreateDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/card/CardDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/payment/PaymentDto.java
  bank-service/src/main/java/org/banka1/bankservice/domains/dtos/user/UserCreateDto.java
  bank-service/src/main/java/org/banka1/bankservice/services/UserService.java
  bank-service/src/test/java/org/banka1/bankservice/IntegrationTest.java
  bank-service/src/test/java/org/banka1/bankservice/cucumber/userservice/UserServiceTests.java
  bank-service/src/test/java/org/banka1/bankservice/cucumber/userservice/UserServiceTestsConfig.java
  bank-service/src/test/java/org/banka1/bankservice/cucumber/userservice/UserServiceTestsSteps.java
  bank-service/src/test/java/org/banka1/bankservice/services/CardServiceTest.java
  bank-service/src/test/java/org/banka1/bankservice/services/UserServiceTest.java
  bank-service/src/test/resources/application-test_it.properties
  bank-service/src/test/resources/features/user-service-tests.feature
Labels: lgtm, size/XXL

#113 account and credit tests
  bank-service/src/test/java/org/banka1/bankservice/controllers/AccountControllerTest.java
  bank-service/src/test/java/org/banka1/bankservice/controllers/CreditControllerTest.java
  bank-service/src/test/java/org/banka1/bankservice/services/AccountServiceTest.java
  bank-service/src/test/java/org/banka1/bankservice/services/CreditServiceTest.java
Labels: lgtm, size/XXL

#115 Manje ispravke
  bank-service/pom.xml
  bank-service/src/main/java/org/banka1/bankservice/controllers/AccountController.java
  bank-service/src/main/java/org/banka1/bankservice/controllers/UserController.java
Labels: size/XS, lgtm

#119 CurrencyExchangeServiceTest testovi
  bank-service/src/test/java/org/banka1/bankaservice/services/CurrencyExchangeServiceTest.java
Labels: size/L

#120 fixed docker compose file -> exchange service depends on user service
  docker-compose.yml
Labels: size/XS

#124 account and credit tests
  bank-service/src/test/java/org/banka1/bankservice/services/AccountServiceTest.java
  bank-service/src/test/java/org/banka1/bankservice/services/CreditServiceTest.java
Labels: size/L, lgtm

#128 Popravka u dobavljanju valuta sa Flask-a
  bank-service/src/main/java/org/banka1/bankservice/services/CurrencyExchangeService.java
Labels: size/S

#129 Promena za racune kod konverzije
  bank-service/src/main/java/org/banka1/bankservice/services/CurrencyExchangeService.java
Labels: size/XS, lgtm

#131 Testiranje prelazi na main granu jer jedino tamo radi prow
  .prow/postsubmits.yaml
Labels: size/XS

#133 Izmenjena greška u pisanju
  .prow/postsubmits.yaml
Labels: size/XS

#134 Izmenjen deployment da bude direktno na production
  .prow/postsubmits.yaml
  companies-service/src/environment.ts
  contracts-service/src/environment.ts
  kubernetes/setup/README.md
Labels: size/S

#135 Izmenjen naziv reference na mongo secret
  kubernetes/companies-service.yaml
  kubernetes/contracts-service.yaml
Labels: size/XS

#136 Ne sme da se koristi regex sa Prefix path tipom
  kubernetes/ingress.yaml
Labels: size/XS
